(function () {
    "use strict";
    const API_URL=String(window.PRORECUP_API_URL||"https://prorecup-backend.onrender.com").replace(/\/+$/,"");
    const params=new URLSearchParams(window.location.search);
    const produit=["backoffice","portail_client","agent_terrain"].includes(params.get("produit"))?params.get("produit"):"inconnu";
    const retours={backoffice:"../index.html",portail_client:"../portail-client/index.html",agent_terrain:"../../agent-app/index.html"};
    const elementRetour=document.getElementById("retour-produit");
    if(elementRetour) elementRetour.href=retours[produit]||"../index.html";
    const message=document.getElementById("message");
    const afficher=function(texte,erreur){if(!message)return;message.textContent=texte;message.classList.toggle("is-error",Boolean(erreur));message.hidden=false;};
    const envoyer=async function(chemin,donnees){const controleur=new AbortController();const minuteur=window.setTimeout(function(){controleur.abort();},12000);try{const reponse=await fetch(API_URL+chemin,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(donnees),signal:controleur.signal});const resultat=await reponse.json().catch(function(){return {};});if(!reponse.ok)throw new Error(resultat.error||resultat.message||"La demande n'a pas pu être traitée.");return resultat;}finally{window.clearTimeout(minuteur);}};
    const tabs=[document.getElementById("tab-password"),document.getElementById("tab-help")];
    const panels=[document.getElementById("panel-password"),document.getElementById("panel-help")];
    tabs.forEach(function(tab,index){if(!tab)return;tab.addEventListener("click",function(){tabs.forEach(function(item,itemIndex){item?.classList.toggle("is-active",itemIndex===index);item?.setAttribute("aria-selected",itemIndex===index?"true":"false");if(panels[itemIndex])panels[itemIndex].hidden=itemIndex!==index;});if(message)message.hidden=true;});});
    const formPassword=document.getElementById("form-password");
    formPassword?.addEventListener("submit",async function(event){event.preventDefault();if(!formPassword.reportValidity())return;const bouton=formPassword.querySelector("button[type=submit]");bouton.disabled=true;if(message)message.hidden=true;try{await envoyer("/api/identity/recovery/password/request",{email:formPassword.elements.email.value.trim()});formPassword.reset();afficher("Si un compte correspond à cette adresse, un lien valable 30 minutes sera envoyé. Pensez à vérifier les courriers indésirables.",false);}catch(erreur){afficher(erreur.name==="AbortError"?"Le service met trop de temps à répondre. Réessayez dans un instant.":erreur.message,true);}finally{bouton.disabled=false;}});
    const formHelp=document.getElementById("form-help");
    formHelp?.addEventListener("submit",async function(event){event.preventDefault();if(!formHelp.reportValidity())return;const donnees=Object.fromEntries(new FormData(formHelp).entries());if(!donnees.emailContact.trim()&&!donnees.telephoneContact.trim()){afficher("Indiquez un e-mail ou un téléphone où l'équipe peut vous contacter.",true);return;}donnees.produitSource=produit;const bouton=formHelp.querySelector("button[type=submit]");bouton.disabled=true;if(message)message.hidden=true;try{const resultat=await envoyer("/api/identity/recovery/help",donnees);formHelp.reset();afficher("Votre demande a été enregistrée. Référence : "+resultat.reference+". L'équipe vérifiera votre identité avant d'agir.",false);}catch(erreur){afficher(erreur.name==="AbortError"?"Le service met trop de temps à répondre. Réessayez dans un instant.":erreur.message,true);}finally{bouton.disabled=false;}});
    const formReset=document.getElementById("form-reset");
    if(formReset){const token=params.get("token")||"";if(!/^[a-f0-9]{64}$/i.test(token)){Array.from(formReset.elements).forEach(function(champ){champ.disabled=true;});afficher("Ce lien est incomplet ou invalide. Demandez un nouveau lien de récupération.",true);}formReset.addEventListener("submit",async function(event){event.preventDefault();if(!formReset.reportValidity())return;const nouveauMotDePasse=formReset.elements.nouveauMotDePasse.value;const confirmationMotDePasse=formReset.elements.confirmationMotDePasse.value;if(nouveauMotDePasse!==confirmationMotDePasse){afficher("La confirmation du mot de passe ne correspond pas.",true);return;}const bouton=formReset.querySelector("button[type=submit]");bouton.disabled=true;try{await envoyer("/api/identity/recovery/password/reset",{token,nouveauMotDePasse,confirmationMotDePasse});formReset.reset();Array.from(formReset.elements).forEach(function(champ){champ.disabled=true;});afficher("Votre mot de passe a été modifié. Vous pouvez maintenant vous reconnecter.",false);}catch(erreur){afficher(erreur.name==="AbortError"?"Le service met trop de temps à répondre.":erreur.message,true);bouton.disabled=false;}});}
}());
