(function(){
    "use strict";
    if(!ProRecup.protegerPage())return;
    ProRecup.initialiserUtilisateur();ProRecup.initialiserDeconnexion();
    const liste=document.getElementById("liste-demandes");const message=document.getElementById("message-page");const filtre=document.getElementById("filtre-statut");
    const statuts=["en_attente_verification","en_attente_validation","actif","suspendu","refuse"];
    const libelles={en_attente_verification:"En attente de vérification",en_attente_validation:"En attente de validation",actif:"Actif",suspendu:"Suspendu",refuse:"Refusé"};
    const texte=function(tag,valeur,classe){const el=document.createElement(tag);el.textContent=valeur||"—";if(classe)el.className=classe;return el;};
    const afficher=function(valeur,erreur){message.textContent=valeur;message.classList.toggle("erreur",Boolean(erreur));message.hidden=false;};
    const rendre=function(demandes){liste.replaceChildren();if(!demandes.length){afficher("Aucune demande ne correspond à ce filtre.",false);return;}message.hidden=true;demandes.forEach(function(d){const carte=document.createElement("article");carte.className="onboarding-card";const head=document.createElement("div");head.className="onboarding-head";const titre=document.createElement("div");titre.append(texte("h3",d.organisation_nom),texte("strong",d.nom_contact));const statut=texte("span",libelles[d.statut]||d.statut,"etiquette");head.append(titre,statut);const meta=document.createElement("div");meta.className="onboarding-meta";meta.append(texte("span",d.email_contact),texte("span",d.telephone_contact),texte("span",[d.ville,d.pays].filter(Boolean).join(", ")),texte("span",d.identifiant_legal));carte.append(head,meta);if(d.message)carte.append(texte("p",d.message));const actions=document.createElement("div");actions.className="onboarding-actions";const select=document.createElement("select");statuts.forEach(function(s){const o=document.createElement("option");o.value=s;o.textContent=libelles[s];o.selected=s===d.statut;select.append(o);});const notes=document.createElement("input");notes.placeholder="Note interne";notes.value=d.notes_internes||"";notes.maxLength=4000;const bouton=texte("button","Enregistrer","bouton-principal");bouton.type="button";bouton.addEventListener("click",async function(){bouton.disabled=true;try{await ProRecup.requete("/api/onboarding/client/"+encodeURIComponent(d.id)+"/statut",{method:"PATCH",body:JSON.stringify({statut:select.value,notesInternes:notes.value})});afficher("Demande mise à jour.",false);await charger();}catch(e){afficher(e.message||"Mise à jour impossible.",true);}finally{bouton.disabled=false;}});actions.append(select,notes,bouton);carte.append(actions);liste.append(carte);});};
    const charger=async function(){afficher("Chargement des demandes…",false);try{const q=filtre.value?"?statut="+encodeURIComponent(filtre.value):"";const resultat=await ProRecup.requete("/api/onboarding/client"+q);rendre(resultat.data||[]);}catch(e){liste.replaceChildren();afficher(e.message||"Impossible de charger les demandes.",true);}};
    filtre.addEventListener("change",charger);charger();
}());
