(function(){
    "use strict";
    if(!ProRecup.protegerPage())return;
    const form=document.getElementById("invitation"),result=document.getElementById("result"),role=document.getElementById("role");
    const user=ProRecup.obtenirUtilisateur();
    if((user?.role||user?.role_nom)!=="admin")Array.from(role.options).filter(o=>o.value!=="agent_valorisation_carbone").forEach(o=>o.remove());
    const show=data=>{result.replaceChildren();result.hidden=false;const text=document.createElement("p");text.textContent=data.message|| (data.code==="EMAIL_SENT"?"Invitation envoyée.":"Invitation créée, mais l'e-mail n'a pas été envoyé. Configurez le fournisseur puis utilisez Nouvelle invitation.");result.append(text);};
    const load=async()=>{try{const r=await ProRecup.requete("/api/identity/invitations");const list=document.getElementById("pending");list.replaceChildren();for(const u of r.data){const row=document.createElement("p");row.textContent=u.nom+" · "+u.email+" · "+u.statut+" ";for(const action of ["renew","cancel"]){const b=document.createElement("button");b.textContent=action==="renew"?"Nouvelle invitation":"Annuler";b.addEventListener("click",async()=>{b.disabled=true;try{const r=await ProRecup.requete(`/api/identity/invitations/${u.id}/${action}`,{method:"POST",body:"{}"});show(r.data);await load();}catch(e){show({message:e.message});}finally{b.disabled=false;}});row.append(b);}list.append(row);}}catch(e){show({message:e.message});}};
    role.addEventListener("change",async()=>{const field=document.getElementById("client-field");field.hidden=role.value!=="client";if(!field.hidden){try{const r=await ProRecup.requete("/api/clients");const select=document.getElementById("clientId");select.replaceChildren();for(const c of r.data||[]){const o=document.createElement("option");o.value=c.id;o.textContent=c.nom;select.append(o);}}catch(e){show({message:e.message});}}});
    form.addEventListener("submit",async e=>{e.preventDefault();if(!form.reportValidity())return;const button=form.querySelector("button");button.disabled=true;const data=Object.fromEntries(new FormData(form));if(data.role!=="client")delete data.clientId;try{const r=await ProRecup.requete("/api/identity/invitations",{method:"POST",body:JSON.stringify(data)});show(r.data);form.reset();await load();}catch(error){show({message:error.message});}finally{button.disabled=false;}});load();
}());
